services:
  server:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=giraf
      - POSTGRES_PASSWORD=bearattack
      - POSTGRES_DB=mydatabase
    depends_on:
      - db
    command: npm start

  client:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - server

  db:
    build: ./dbServer
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    postgres_data:
