services:
  server:
    image: ghcr.io/dendanskemetode/dendanskedonation/server:latest
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=giraf
      - POSTGRES_PASSWORD=bearattack
      - POSTGRES_DB=mydatabase
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - db
    command: npm start

  client:
    image: ghcr.io/dendanskemetode/dendanskedonation/client:latest
    build:
      context: ./frontend
      args:
        - REACT_APP_STRIPE_PUBLISHABLE_KEY=pk_test_51TCd9b4HA5votMsYw5mKy2hgwPvkgIwXgTVHv2HP4sLsRqotExeTNKBQeN4jAxNnxEaIghAFiZy5Xa7YuY2kr6Vm004XE27mIW
    ports:
      - "80:80"
    environment:
      - REACT_APP_STRIPE_PUBLISHABLE_KEY=pk_test_51TCd9b4HA5votMsYw5mKy2hgwPvkgIwXgTVHv2HP4sLsRqotExeTNKBQeN4jAxNnxEaIghAFiZy5Xa7YuY2kr6Vm004XE27mIW
    depends_on:
      - server

  db:
    image: ghcr.io/dendanskemetode/dendanskedonation/db:latest
    build: ./dbServer
    container_name: postgres_db
    environment:
      POSTGRES_USER: giraf
      POSTGRES_PASSWORD: bearattack
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
