services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=giraf
      - POSTGRES_PASSWORD=bearattack
      - POSTGRES_DB=mydatabase
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_STRIPE_PUBLISHABLE_KEY=pk_test_51TCd9b4HA5votMsYw5mKy2hgwPvkgIwXgTVHv2HP4sLsRqotExeTNKBQeN4jAxNnxEaIghAFiZy5Xa7YuY2kr6Vm004XE27mIW
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server

  db:
    build: ./dbServer
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: giraf
      POSTGRES_PASSWORD: bearattack
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
