services:
  server:
    image: ghcr.io/dendanskemetode/dendanskedonation/server:latest
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  client:
    image: ghcr.io/dendanskemetode/dendanskedonation/client:latest
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - server

  db:
    image: ghcr.io/dendanskemetode/dendanskedonation/db:latest
    build: ./dbServer
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
